services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: zxcv1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: hta
      MYSQL_PASSWORD: zxcv1234
    ports:
     - 3306:3306
    volumes:
     - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10
  spring-app:
    build: .
    ports:
      - 80:80
    depends_on:
      mysql-db:
        condition: service_healthy  
volumes:
  mysql-data:

