server :
  port : 80

logging:
  level:
    "[org.springframework.security]": info
    "[com.example.demo.mapper]": trace

spring:
# 커넥션풀(DataSource) 설정
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: hr
    password: zxcv1234
# JSP 뷰 페이지 경로 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# mybatis 설정
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.example.demo.vo
  configuration:
    jdbc-type-for-null: 'NULL'