server:
  port: 80

spring:
  application:
    name: app6
  profiles:
    active:
    - prod

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.vo
  configuration:
    jdbc-type-for-null: 'NULL'

