spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db:3306/mydb?useSSL=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: hta
    password: zxcv1234